#!/bin/sh

# build & run karel program

KARELPATH="/workspaces/CS106A-codespace/assignment1/karel.jar"

/usr/bin/javac -cp $KARELPATH $1 && 
(/usr/bin/java -cp $(dirname $1):$KARELPATH "$(basename ${1%.*})" || echo "Error during execution") || 
echo "Error during compilation"
