#!/bin/sh

# build & run your java program

ACMPATH="/home/$(whoami)/.local/lib/cs106a/acm.jar"
KARELPATH="/home/$(whoami)/.local/lib/cs106a/karel.jar"
YAHTZEEPATH="/home/$(whoami)/.local/lib/cs106a/yahtzeelib.jar"

SOURCE_FILES=$(dirname $1)/*.java
/usr/bin/javac -cp $ACMPATH:$KARELPATH:$YAHTZEEPATH $SOURCE_FILES &&
(/usr/bin/java -cp $(dirname $1):$ACMPATH:$KARELPATH:$YAHTZEEPATH "$(basename ${1%.*})" || echo "Error during execution") ||
echo "Error during compilation"
